menu:
	home: /
	about: /About/
	original: /Original/
	project: /Project/
	music: /Music/
	others: /Others/
	# blog: /Blog/
	# archives: /Blog/archives/

widgets:
	- category
	- tag
	- archive
	# - recent_posts
