menu:
	home: /
	about: /about/
	original: /original/
	project: /project/
	music: /music/
	others: /others/
	#blog: /blog/
	#archives: /blog/archives/

	# Original 的子選單（不要移除 parent，template 會尋找 original_submenu）
	original_submenu:
		parent: original
		submenu:
			archives: /blog/archives/

widgets:
	- category
	- tag
	- archive
	# - recent_posts
