menu:
	home: /
	about: /about/
	original: /original/
	project: /project/
	music: /music/
	others: /others/
	# blog: /blog/
	# archives: /blog/archives/

widgets:
	- category
	- tag
	- archive
	# - recent_posts
